// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCacZfaIlR2Wq7p_9JFY2LxtQhEjqLOECs',
    appId: '1:547342909947:web:3c68ceed3b3d1c47fc4b5e',
    messagingSenderId: '547342909947',
    projectId: 'gardening-app-87c91',
    authDomain: 'gardening-app-87c91.firebaseapp.com',
    databaseURL: 'https://gardening-app-87c91-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gardening-app-87c91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMpAjJ-8HRezExOypzd4JXskY-dZcaBvg',
    appId: '1:547342909947:android:071c03ba873cc7d9fc4b5e',
    messagingSenderId: '547342909947',
    projectId: 'gardening-app-87c91',
    databaseURL: 'https://gardening-app-87c91-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gardening-app-87c91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAklUuR7qZEdKCL0cy0WexwmhxiXBDZlM4',
    appId: '1:547342909947:ios:1737405b69d4dd00fc4b5e',
    messagingSenderId: '547342909947',
    projectId: 'gardening-app-87c91',
    databaseURL: 'https://gardening-app-87c91-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gardening-app-87c91.appspot.com',
    iosClientId: '547342909947-3m59s5k0hbfgivoasioieh5tr8keaug4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gardeningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAklUuR7qZEdKCL0cy0WexwmhxiXBDZlM4',
    appId: '1:547342909947:ios:01e8237102430d9ffc4b5e',
    messagingSenderId: '547342909947',
    projectId: 'gardening-app-87c91',
    databaseURL: 'https://gardening-app-87c91-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gardening-app-87c91.appspot.com',
    iosClientId: '547342909947-ijaak8e5ulj3ccmed34oenf9s5kdfiro.apps.googleusercontent.com',
    iosBundleId: 'com.example.gardeningApp.RunnerTests',
  );
}
